sudo: false

matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      language: python
      python:
        - 2.6
    - os: linux
      language: python
      python:
        - 2.7
    - os: linux
      language: python
      python:
        - 3.5
    - os: linux
      language: python
      python:
        - 3.6
    - os: linux
      language: python
      python:
        - 3.7

before_install:
    # osx deps
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall --ignore-dependencies python; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi

install:
    - pip install six
    ## must upgrade pip/setuptools otherwise the install of importlib breaks
    #- if [ ${TRAVIS_PYTHON_VERSION} != "2.6" ]; then pip install -U "pip==18.1" "setuptools==40.5.0"; fi
    #- pip install importlib
    - pip install codecov
    - python setup.py install

script:
    - coverage run -m soma_workflow.test

after_success:
    - codecov
