sudo: false

matrix:
  include:
    - os: osx
      language: generic
      name: python 2.7
    - os: linux
      language: python
      name: python 2.6
      python:
        - 2.6
    - os: linux
      language: python
      name: python 2.7
      python:
        - 2.7
    - os: linux
      language: python
      name: python 3.5
      python:
        - 3.5
    - os: linux
      language: python
      name: python 3.6
      python:
        - 3.6

before_install:
    # osx deps
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall --ignore-dependencies python; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi

install:
    - pip install six
    - if [ ${TRAVIS_PYTHON_VERSION} == "2.6" ]; then pip install importlib; fi
    - pip install codecov
    - python setup.py install
    - python --version

script:
    - coverage run -m soma_workflow.test

after_success:
    - codecov
